spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca_db
    username: postgres
    password: denis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false